/*SCRIPTS DE ELIMINACIÓN*/

DROP TABLE HISTORIAL_MONEDA;
DROP TABLE FEEDBACK;
DROP TABLE TRANSACCION;
DROP TABLE CATEGORIA;
DROP TABLE CUENTA;
DROP TABLE BANCO;
DROP TABLE LUGAR;
DROP TABLE ESTATUS;
DROP TABLE MONEDA;
DROP TABLE PERFIL;
DROP TABLE USUARIO;